FROM ubuntu:22.04
LABEL author="Emilie Deprez"
LABEL version="1.0"
WORKDIR /app
RUN apt-get update
RUN apt-get install tcpdump --yes
RUN apt-get install frr --yes
RUN apt-get install iputils-ping --yes
